spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog_system?useSSL=false&characterEncoding=utf8
    username: root
    password: 050908
    driver-class-name: com.mysql.cj.jdbc.Driver
#  rabbitmq:
#    host: localhost
#    port: 5672
#    stream:
#      username: Chiu-xaH
#      password: 050908
#    listener:
#      simple:
#        prefetch: 1
#  data:
#    redis:
#      host: localhost
#      port: 6379
#      lettuce:
#        pool:
#          max-active: 8
#          max-idle: 8
#          min-idle: 0
#          max-wait: 100ms


file:
  upload-dir: D:/blogUpload/image
  location-url: /upload/image/

#  mybatis:
#  mapper-locations: classpath:mapper/**Mapper.xml

